Repository hivemindapp/hivemind-backend, pull requests merged in 2021-08, with the labels that each got.

#19 Travis CI/CD
  .gitignore
  .travis.yml
  app/controllers/graphql_controller.rb
  app/graphql/hivemind_be_schema.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
Labels: bug, BE

#20 Fix GraphQL deployment
  config/initializers/assets.rb
Labels: bug, BE

#21 Fix graphql config
  config/application.rb
Labels: bug, BE

#22 Update posts endpoint and testing
  Gemfile
  Gemfile.lock
  app/graphql/types/post_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/user_type.rb
  config/initializers/cors.rb
  spec/factories/posts.rb
  spec/factories/users.rb
  spec/graphql/types/post_type_spec.rb
  spec/graphql/types/query_type/posts_spec.rb
  spec/graphql/types/user_type_spec.rb
  spec/spec_helper.rb
Labels: ITERATION 1, BE, endpoint

#24 Endpoint to create a new post ( also completes user posts endpoint)
  .travis.yml
  app/graphql/mutations/posts/create_post.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  config/initializers/assets.rb
  db/seeds.rb
  spec/factories/posts.rb
  spec/factories/users.rb
  spec/graphql/mutations/posts/create_post_spec.rb
  spec/graphql/types/query_type/user_posts_spec.rb
Labels: BE, endpoint

#28 Update Travis for staging branch
  .travis.yml
Labels: project-setup, BE

#35 Update all posts ordering to reverse chronological
  app/graphql/types/query_type.rb
  spec/graphql/types/query_type/posts_spec.rb
Labels: BE
